"""Rule constants from Adaptive Climate 0d32c1f; see ADAPTIVE_CLIMATE_LICENSE."""

RULE_PRIORITY_OSCILLATION = 3
RULE_PRIORITY_OVERSHOOT = 2
RULE_PRIORITY_SLOW_RESPONSE = 1
RULE_HYSTERESIS_BAND_PCT = 0.20
MIN_OUTDOOR_TEMP_RANGE = 3.0
SLOW_RESPONSE_CORRELATION_THRESHOLD = 0.6
